### ISSUE TITLE
Interest in UI Designer?

### ISSUE THREAD

**Issue by fpw23** [ahuggins-nhs/node-x12#19]
@ahuggins-nhs Do you think there is a need for a UI/Web API/ Microservice thing for this project?  I have been able to use this library and generate/parse the EDI I need with ease.  I have done this all in my test app using some dynamic scripts.  Now is the time to implement this into my main project and as I sat down and thought about it how to do this I feel like my brain is pulling me toward making this a microservice.  That got me thinking, how many other people could use an scriptable EDI microservice in their app designs?  Do a lot of people use EDI and if so do they build support for it directly into their apps or do they abstract it out as a service?

**Comment by ahuggins-nhs** [comment]
In my limited experience, it goes both ways. We're using this in a microservice in MS Azure which we call from a few different services, and we also use it as an embedded library for grabbing some quick info from ISA/GS/ST headers.

With my biases, I would lean toward a reusable microservice that can be extended and only embed the lib as needed for metadata. That's based totally on what we've done so far, I have no empirical evidence to really reason through which way is "better".

**Comment by ahuggins-nhs** [comment]
@fpw23 There's this [comment](https://github.com/ahuggins-nhs/node-x12/issues/8#issuecomment-668996525) by sambacha; looks like they're building out a microservice in typescript.

**Comment by ahuggins-nhs** [comment]
@fpw23 Closing for now. I love this idea and it might get implemented as a package in `js-edi`(?) if interest picks up again.
